# Generated by Django 4.2.6 on 2024-07-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0011_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='intials',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='proficiency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], default=('In Active', 'In Active'), max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
