# Generated by Django 4.2.6 on 2024-07-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0013_alter_userprofile_intials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='intials',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
