# Generated by Django 4.2.6 on 2024-07-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0014_alter_userprofile_intials'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Super User', 'Super User'), ('Manager', 'Manager')], default=('User', 'User'), max_length=50),
        ),
    ]
