# Generated by Django 4.2.6 on 2024-07-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0015_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Super User', 'Super User'), ('Manager', 'Manager')], max_length=50),
        ),
    ]
