# Generated by Django 4.2.6 on 2024-07-08 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0019_alter_task_assigned_to_project_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='todoapp.project'),
        ),
    ]
