# Generated by Django 4.2.6 on 2024-07-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0022_alter_task_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='assignedTo',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='taskName',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='taskStatus',
        ),
    ]
