# Generated by Django 4.2.6 on 2024-07-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0023_rename_assigned_to_task_assignedto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
