# Generated by Django 4.2.6 on 2024-07-18 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0025_alter_task_assignedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskStatus',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='todoapp.card'),
        ),
    ]
