# Generated by Django 4.2.6 on 2024-07-18 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapp', '0027_alter_task_taskstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignedTo',
            field=models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_groups',
            field=models.ManyToManyField(related_name='group_tasks', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todoapp.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.card'),
        ),
    ]
