# Generated by Django 4.2.6 on 2024-07-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('todoapp', '0028_alter_task_assignedto_alter_task_assigned_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, related_name='group_tasks', to='auth.group'),
        ),
    ]
