# Generated by Django 4.2.6 on 2024-07-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0029_alter_task_assigned_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proj_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
