# Generated by Django 5.0.6 on 2024-07-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0032_alter_task_project_projects_assignedto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='assignedTo',
        ),
    ]
