# Generated by Django 5.0.6 on 2024-07-19 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0033_remove_projects_assignedto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projname', models.CharField(max_length=100)),
                ('proj_date', models.DateField(blank=True, null=True)),
                ('assignedTo', models.ManyToManyField(related_name='assigned_project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
