# Generated by Django 5.0.6 on 2024-07-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0035_remove_userprofile_intials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
    ]
