# Generated by Django 5.0.6 on 2024-07-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0036_remove_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='manager',
            field=models.CharField(default='Default Manager', max_length=255),
        ),
    ]
