# Generated by Django 5.0.6 on 2024-07-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0039_alter_task_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dead_line',
            new_name='deadline',
        ),
    ]
