# Generated by Django 5.0.6 on 2024-07-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0040_rename_dead_line_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('UI/UX Designer', 'UI/UX Designer'), ('Backend Developer ', 'Backend Developer'), ('Full Stack Developer ', 'Full Stack Developer'), ('Cloud Developer ', 'Cloud Developer')], max_length=50, null=True),
        ),
    ]
