# Generated by Django 5.0.6 on 2024-07-23 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0044_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todoapp.projects'),
        ),
    ]
