# Generated by Django 5.0.6 on 2024-07-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0046_remove_projects_techstack'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
