# Generated by Django 5.0.6 on 2024-07-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0047_projects_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='profile_photo',
        ),
    ]
