# Generated by Django 5.0.6 on 2024-07-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0054_alter_projects_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
