# Generated by Django 5.0.6 on 2024-07-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0058_remove_projects_team_projects_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
