# Generated by Django 5.0.6 on 2024-07-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0063_alter_message_date_time_alter_task_taskname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
