# Generated by Django 5.0.7 on 2024-08-02 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0066_alter_message_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='flagged'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='todoapp.message'),
        ),
    ]
