# Generated by Django 5.0.7 on 2024-08-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0067_message_is_flagged_message_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='cover',
            field=models.CharField(blank=True, default='#ffff', max_length=100, null=True),
        ),
    ]
