# Generated by Django 5.0.7 on 2024-08-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0069_remove_task_enddate_task_achieved_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='achieved_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
