# Generated by Django 5.0.7 on 2024-08-06 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0070_alter_task_achieved_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignedTo',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
