# Generated by Django 5.0.7 on 2024-08-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0071_alter_task_assignedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskName',
            field=models.CharField(max_length=255),
        ),
    ]
