# Generated by Django 5.0.7 on 2024-08-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0072_alter_task_taskname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photo',
        ),
    ]
