# Generated by Django 5.0.7 on 2024-08-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0073_remove_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
