# Generated by Django 5.0.7 on 2024-08-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0075_projects_project_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('username', models.CharField(max_length=150)),
                ('task_name', models.CharField(max_length=255)),
                ('progress_percentage', models.FloatField()),
            ],
        ),
    ]
