# Generated by Django 5.0.7 on 2024-08-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0076_progressdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='achieved_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
