# Generated by Django 5.0.7 on 2024-08-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0078_alter_task_assignedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, choices=[('User', 'User'), ('Super User', 'Super User'), ('Manager', 'Manager'), ('Team Lead', 'Team Lead')], default='User', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('UI/UX Designer', 'UI/UX Designer'), ('Backend Developer', 'Backend Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('Cloud Developer', 'Cloud Developer')], max_length=50, null=True),
        ),
    ]
