# Generated by Django 5.0.7 on 2024-08-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0079_alter_userprofile_designation_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='ETA',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
