# Generated by Django 5.0.7 on 2024-08-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0081_alter_message_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_wallet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
